branches:
  only:
    - master
    - develop

addons:
  postgresql: '9.3'

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database cumulus_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate

deploy:
  provider: heroku
  api_key:
    master:
      secure: QxU8X22oD170+YrSyv3Tm8FH6UrcIBqnDSOV54I25AZGWVxCSPWUUDv89yYmXDckUK7yfW9WS+FwpRy3R+Oj14aL90zoxeTYC2QPO8mn18KwxRouJus7P4qy+2MD8YF4Ule5vyK8hJFcsv6dmRjaPcvkkyRGfeDKMivBT8C6olsvs/KmgAr+UCQWQXe/zDWN/6wcU1NcH5Fe7ecqyiA0mgL4RkqpkVTJ24KdUc+pFbBP9ift4cseH9BPXmLcIp6htihUjQp8eMGnoshlIdlhleLyGk5/Pjn93ykgKwwkC2f81jFBNn9TQCRPc4WvFsQBxbq8gd6UG6ju6sXS/3SsQ4HRBS+g7BuOCBabLb9piXYefjrU5c2K3o2NJwJjI+rp77hPD7p0eCnHBjPIEev5ZyuRR5sdYRFD0DV23wWY2MszAnaW3bREo+H/rDtjsE0LPF9TBBWt9N4YxhvvGM7CPoJE636DKsKrNaZDPe78x5gY1tKkkNeT5IAgriiF7STSKuLPnEHKMDiSV+nLorIjg1TujBMb+qMnQCIV+c3oKZws/+jkijVvc0L5ook0jmHHbin7EpEtcOeGhnnnxYV9S5qNSJ1fva7kyzL/cspc7CSpb9g710u5FFkL6nEv8Rua0INhuEfIW3JbhBsC9JNCyg1kkkYrFQaS5l5d6T8zhvw=
    develop:
      secure: D8R3aUQ+hKsfi2C+KGzdrtStBVsYzFakqXlnRWiiCgWOwHxYGKGS7S2UDn3wPZbiAjOgHrUxMTqZZn1SSACI73nzNs0D5wVWuKbXRTcm0lDlC5EvE2owhVHeRLX2RMVnqxJ1fbI4hR0iMdC070CtBhLBJ2KPwHf12KlCn7DGI85cd+t41PUg4iomTcaWfYkFoG3fE7EEer8hxc1hPJN/TyDi4Yh0FHFV9xssNSHhaDXvQR6w0DrDD6jQF5mtZScGHaemqUyOa+TVDFtxUVyYyj3sw9JApSX9cRtlRqpKwZ3lqRUAY8beOs2kTu7ey1dTyqDiEVkLax8dECCQAOU6mXU7ATziFUlwU8QMRi0HjnPxQgb8GyU4M/poxmQsgTmSYkgtJApV/Y0JCBztgltphYkgKMZAUQ/PeZFxkrr6OeCPevYw5FNuVjakDyJBgEZN3mY+bLJ0Q+YZMcheSqQ/xyowgNtGq6ZGshmY21HjWsmsZD8Rjm9+iRnhzMwAHqLNLHNSPpmy9afGRowD5MgYPgO5ev8rlMvKvjS9ZSS9KGGGnrhIOELQvuQbiqzTSJoXY1d3Zdxtsjv6Z7xjWzAMNCrDItYejEPKaQ7nLYSWH/BEr0YxJvFmMGPBWzK6Z73wFKVnX880KCajDeqn6SxROGFTkzRNCiFsluAo8Gr5Wqs=
  app:
    master: production-cumulus
    develop: staging-cumulus
  on:
    repo: soaringbook/cumulus
  run:
    - "rake db:migrate"
    - restart
  skip_cleanup: true
