branches:
  only:
    - master
    - develop

addons:
  postgresql: '9.3'

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database cumulus_test;' -U postgres

