# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdb7c64280d510a3a04783d55acb8bb74a37d382dc6859ba813ae2e0604877af3bdd64d0affd14f8f9ec88a93028f6ec1e91e497155297de4741c4529b35c8ef

test:
  secret_key_base: 370030c90a390ba0916668e135b2d0da190f231e531c2d0524167f1b62d4084f2891b7a808f1be12f62a770b1a38e85d51cddafc5afc89adc14d37ff773f94f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
